spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auleWeb
    username: root
    password: mysql
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081